
<form action="<?php echo $this->getUrl('articles/index/post'); ?>" id="brochureform" method="post">
    <ul class="form-list">
        <li><label>Name</label><br>
            <input class="input-text required-entry" id="name" name="name" style="width: 1250px;" type="text"></li>
        <li><label>Description</label><br>
            <textarea class="input-text required-entry" id="dscr" name="dscr" style="width: 1500px;" type="text"></textarea></li>

    </ul><button class="button btn-add" type="submit"><span>Add</span></button>
</form>